---
- hosts: WebServer
  become: yes
  tasks: 
  - name: install apache
    package:
      name: apache2
      state: present
      update_cache: yes
    when: ansible_os_family == "Debian"
  - name: install apache
    package:
      name: httpd
      state: ansible_is_family =="RedHat"
