---
- hosts: WebServer
  become: yes
  vars:
    package_name: httdp
  tasks:
  - name: install apache
    package:
      name: "{{ package_name }}"
      state: present
  - name: install utility
    package:
      name: "{{utility_package}}"
      state: present