---
- hosts: WebServer
  become: yes
  tasks:
  - name: apache2
    state: present
    update_cache: yes
  notify:
  - start apache
  - name: update packages & installing apache
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - php
      - libapache2-mod-php
      - php-mysql
      - apache2
      - php-cli
    notify:
      - restart apache
  - name: copy file
    copy: 
      src: info.php
      dest: /var/www/html/info.php
    notify:
    - restart apache
  handlers:
  - name: restart apache
    service:
      name: apache2
      enabled: yes
      state: restarted
  - name: start apache
    service:
      name: apache2
      enabled: yes
      state: started


