---
- hosts: AppServer
  become: yes
  tasks:
  - name: Installs nginx web server
    apt: 
      name: nginx 
      state: present 
      update_cache: true
    notify:
    - start nginx
  - name: Upload default index.html for volumes
    copy:
      src: static_files/index.html 
      dest: /usr/share/nginx/www/ 
      mode: 0644
  handlers:
  - name: start nginx
    service: 
      name: nginx 
      state: present