---
- hosts: ip-172-31-47-70.eu-west-1.compute.internal
  gather_facts: no
  become: yes
  tasks:
  - name: check current system date
    command: date
    register: date
  
  - name: Print the current system date
    debug: var=date.stdout